apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.character.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "startrekcharacter.name" . }}
    chart: {{ template "startrekcharacter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "startrekcharacter.name" . }}
    release: {{ .Release.Name }}
